-- 都道府県セット (generate_prefecture_sql.py で自動生成)
-- 全チームを対象に上書き更新する

UPDATE mst_team SET prefecture = '兵庫' WHERE id = 2;  -- 芦屋海浜公園
UPDATE mst_team SET prefecture = '千葉' WHERE id = 3;  -- ＣＳ南行徳
UPDATE mst_team SET prefecture = '千葉' WHERE id = 4;  -- セ・おおたか
UPDATE mst_team SET prefecture = '千葉' WHERE id = 5;  -- セ・八千代台
UPDATE mst_team SET prefecture = '千葉' WHERE id = 6;  -- セ・千葉みなと
UPDATE mst_team SET prefecture = '千葉' WHERE id = 7;  -- セ・市川
UPDATE mst_team SET prefecture = '千葉' WHERE id = 8;  -- セ・志津
UPDATE mst_team SET prefecture = '千葉' WHERE id = 9;  -- セ・我孫子
UPDATE mst_team SET prefecture = '千葉' WHERE id = 10;  -- セ・新浦安
UPDATE mst_team SET prefecture = '千葉' WHERE id = 11;  -- セ・本八幡
UPDATE mst_team SET prefecture = '千葉' WHERE id = 12;  -- セ・松戸
UPDATE mst_team SET prefecture = '千葉' WHERE id = 13;  -- セ・柏
UPDATE mst_team SET prefecture = '千葉' WHERE id = 14;  -- セ・流山
UPDATE mst_team SET prefecture = '千葉' WHERE id = 15;  -- セ・稲毛海岸
UPDATE mst_team SET prefecture = '千葉' WHERE id = 16;  -- セ・茂原
UPDATE mst_team SET prefecture = '千葉' WHERE id = 17;  -- セ・蘇我
UPDATE mst_team SET prefecture = '千葉' WHERE id = 18;  -- セ・袖ヶ浦
UPDATE mst_team SET prefecture = '千葉' WHERE id = 19;  -- セ・袖ケ浦
UPDATE mst_team SET prefecture = '千葉' WHERE id = 20;  -- セ・谷津
UPDATE mst_team SET prefecture = '千葉' WHERE id = 21;  -- セ・館山
UPDATE mst_team SET prefecture = '千葉' WHERE id = 22;  -- セ・馆山
UPDATE mst_team SET prefecture = '千葉' WHERE id = 23;  -- 南行徳
UPDATE mst_team SET prefecture = '千葉' WHERE id = 24;  -- 曽谷・セ
UPDATE mst_team SET prefecture = '千葉' WHERE id = 25;  -- 浦安
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 28;  -- ザバス和光
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 29;  -- セ・久喜
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 30;  -- セ・大宮宮原
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 31;  -- セ・岩槻
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 32;  -- セ・川越
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 33;  -- セ・志木
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 34;  -- セ・新三郷
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 35;  -- セ・新都心
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 36;  -- セ・桶川北本
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 37;  -- セ・越谷
UPDATE mst_team SET prefecture = '埼玉' WHERE id = 38;  -- セ・越谷ＬＴ
UPDATE mst_team SET prefecture = '東京' WHERE id = 39;  -- Ｇ－ＳＰＡ
UPDATE mst_team SET prefecture = '東京' WHERE id = 40;  -- セ・ときわ台
UPDATE mst_team SET prefecture = '東京' WHERE id = 41;  -- セ・上池袋
UPDATE mst_team SET prefecture = '東京' WHERE id = 42;  -- セ・下北沢
UPDATE mst_team SET prefecture = '東京' WHERE id = 43;  -- セ・亀有
UPDATE mst_team SET prefecture = '東京' WHERE id = 44;  -- セ・八王子
UPDATE mst_team SET prefecture = '東京' WHERE id = 45;  -- セ・南千住
UPDATE mst_team SET prefecture = '東京' WHERE id = 46;  -- セ・南青山
UPDATE mst_team SET prefecture = '東京' WHERE id = 47;  -- セ・大森
UPDATE mst_team SET prefecture = '東京' WHERE id = 48;  -- セ・大泉学園
UPDATE mst_team SET prefecture = '東京' WHERE id = 49;  -- セ・天王洲
UPDATE mst_team SET prefecture = '東京' WHERE id = 50;  -- セ・府中
UPDATE mst_team SET prefecture = '東京' WHERE id = 51;  -- セ・成城
UPDATE mst_team SET prefecture = '東京' WHERE id = 52;  -- セ・成瀬
UPDATE mst_team SET prefecture = '東京' WHERE id = 53;  -- セ・東十条
UPDATE mst_team SET prefecture = '東京' WHERE id = 54;  -- セ・清瀬
UPDATE mst_team SET prefecture = '東京' WHERE id = 55;  -- セ・用賀
UPDATE mst_team SET prefecture = '東京' WHERE id = 56;  -- セ・目黒
UPDATE mst_team SET prefecture = '東京' WHERE id = 57;  -- セ・福生
UPDATE mst_team SET prefecture = '東京' WHERE id = 58;  -- セ・自由が丘
UPDATE mst_team SET prefecture = '東京' WHERE id = 59;  -- セ・葛西
UPDATE mst_team SET prefecture = '東京' WHERE id = 60;  -- セ・蒲田
UPDATE mst_team SET prefecture = '東京' WHERE id = 61;  -- セ・西台
UPDATE mst_team SET prefecture = '東京' WHERE id = 62;  -- セ・西新井
UPDATE mst_team SET prefecture = '東京' WHERE id = 63;  -- セ・西東京
UPDATE mst_team SET prefecture = '東京' WHERE id = 64;  -- セ・阿佐谷
UPDATE mst_team SET prefecture = '東京' WHERE id = 65;  -- セ・青砥
UPDATE mst_team SET prefecture = '東京' WHERE id = 66;  -- 墨田区体育館
UPDATE mst_team SET prefecture = '栃木' WHERE id = 67;  -- セ・Ｆ宇都宮
UPDATE mst_team SET prefecture = '栃木' WHERE id = 68;  -- セ・南宇都宮
UPDATE mst_team SET prefecture = '栃木' WHERE id = 69;  -- セ・宇都宮
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 70;  -- ザバス八景
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 71;  -- ザバス川崎
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 72;  -- ザバス藤が丘
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 73;  -- ザバス金沢八
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 74;  -- ザバス鶴見
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 75;  -- セ・Ｆ東戸塚
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 76;  -- セ・Ｓ湘南台
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 77;  -- セ・セン南
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 78;  -- セ・トレッサ
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 79;  -- セ・二俣川
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 80;  -- セ・川崎
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 81;  -- セ・市ヶ尾
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 82;  -- セ・平塚
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 83;  -- セ・慶應日吉
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 84;  -- セ・戸塚
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 85;  -- セ・新川崎
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 86;  -- セ・本郷台
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 87;  -- セ・東戸塚
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 88;  -- セ・横浜
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 89;  -- セ・武蔵小杉
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 90;  -- セ・湘南ＬＴ
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 91;  -- セ・溝ノ口
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 92;  -- セ・能見台
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 93;  -- セ・藤沢
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 94;  -- セ・長津田
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 95;  -- 八景
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 96;  -- 川崎
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 97;  -- 金沢八景
UPDATE mst_team SET prefecture = '神奈川' WHERE id = 98;  -- 颯介セ・慶應日吉
UPDATE mst_team SET prefecture = '福島' WHERE id = 99;  -- セ・福島
UPDATE mst_team SET prefecture = '福島' WHERE id = 100;  -- セ・郡山
UPDATE mst_team SET prefecture = '群馬' WHERE id = 101;  -- セ・前橋
UPDATE mst_team SET prefecture = '群馬' WHERE id = 102;  -- セ・高崎
-- 自動マッチ不可チーム（手動で設定）
UPDATE mst_team SET prefecture = '千葉' WHERE id = 26;  -- クリーンスパ
UPDATE mst_team SET prefecture = '千葉' WHERE id = 27;  -- セ・長沼
UPDATE mst_team SET prefecture = NULL   WHERE id = 1;   -- ミズノＭＴ（都道府県不明のためNULL）
